@startuml rdcu-redemarrer-jeu
skinparam style strictuml
skinparam defaultFontName Verdana
title RDCU pour redemarrerJeu

participant ":JeuDeDes" as c
participant "joueurs:\nMap<String, Joueur>" as jm

->c : redemarrerJeu()
note right: selon Contrôleur\n(JeuDeDes est l'objet racine)

c -> jm : clear()
note right: selon Expert

@enduml
